language: node_js
node_js:
  - "7"
  - "6"
  - "4"
  - "0.12"
os:
  - osx
matrix:
  fast_finish: true
  include:
    - node_js: "7"
      os: linux
      sudo: false
      dist: trusty
    - node_js: "6"
      os: linux
      sudo: false
      dist: trusty
    - node_js: "4"
      os: linux
      sudo: false
      dist: trusty
    - node_js: "0.12"
      os: linux
      sudo: false
      dist: trusty
